//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : DetFactura.cs
//  @ Date : 4/12/2023
//  @ Author : 
//
//


public class DetFactura {
public string Producto {  get; set; }
public double Cantidad { get; set; }
public double Precio {  get; set; }
public double Impuesto {  get; set; }
public double SubTotal {  get; set; }
public double Total { get; set; } 
}
